# Generated by Django 2.2.7 on 2019-11-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='johntest',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='johntest',
            name='article_content',
        ),
    ]
