# Generated by Django 2.2.7 on 2019-11-25 23:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191125_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='johntest',
            name='title',
        ),
        migrations.AddField(
            model_name='johntest',
            name='article_content',
            field=tinymce.models.HTMLField(default='Content'),
        ),
        migrations.AddField(
            model_name='johntest',
            name='article_title',
            field=models.CharField(default='0000000', max_length=200),
        ),
    ]
