# Generated by Django 2.2.7 on 2019-11-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191125_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='johntest',
            name='title',
            field=models.CharField(default='foobar', max_length=200),
            preserve_default=False,
        ),
    ]
