# Generated by Django 2.2.7 on 2019-11-25 23:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_johntest_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='johntest',
            name='article_content',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
