# Generated by Django 2.2.7 on 2019-11-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191125_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='johntest',
            name='title',
            field=models.CharField(default='Hello', max_length=200),
        ),
    ]
